version: '3.4'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=teste@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433" 
    networks:
      - mynetwork 
    healthcheck: 
      
      test: ["CMD-SHELL", "/bin/bash -c 'echo > /dev/tcp/localhost/1433 || exit 1'"]
      interval: 10s
      timeout: 5s
      retries: 100
      start_period: 60s
    volumes: 
      - sqlserver_data:/var/opt/mssql

  
  gestaodetarefasapi: 
    build:
      context: . 
      dockerfile: Dockerfile        
    ports:
      - "8080:8080" 
      - "8081:8081" 
    environment:
      - ASPNETCORE_URLS=http://+:8080 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=GestaoDeTarefasDB;User Id=sa;Password=teste@123;TrustServerCertificate=True;
    depends_on: 
      sqlserver:
        condition: service_healthy
    networks:
      - mynetwork

networks:
  mynetwork:

volumes: 
  sqlserver_data: